### ISSUE TITLE
Images saved are thumbnails

### ISSUE THREAD

**Issue by Deleetdk** [Deleetdk/OKCubot2#1]
The current version saves images, but there are two problems:

1.
The images saved are thumbnails (225x225), not the real size images.

2.
The profile picture is saved twice. The second saving is an extra small thumbnail (82x82).

**Comment by tomwalter2287** [comment]
I removed the code to save a small thumbnail(82x82).
So I think this issue is solved.

**Comment by Deleetdk** [comment]
Only (2) is solved. The rest of the images are still saved in small size (225x225). The images on the site are much larger. E.g. https://k0.okccdn.com/php/load_okc_image.php/images/0x0/0x0/0/333962413928386101.jpeg?v=1

From user https://www.okcupid.com/profile/Cloudy7_taco

**Comment by tomwalter2287** [comment]
I pushed new version.

It saves only 225*255 thumbnail.

**Comment by Deleetdk** [comment]
I don't want to save 255x255 thumbnails. I want to save the full size pictures. In the above case, the full size is 1125 x 1500.

**Comment by tomwalter2287** [comment]
I pushed new version.
This issue is solved in this version.

**Comment by Deleetdk** [comment]
I tested the new version. This issue is fixed.
