### ISSUE TITLE
The location of the data output folder depends on the calling location

### ISSUE THREAD

**Issue by Deleetdk** [Deleetdk/OKCubot2#2]
I noticed that the location of the data folder depends on where one calls the scraper from. If I call it from within the folder, it gets placed in `OKCubot2/OKcu/data`. However, if I call it from e.g. the OKCubot2 folder, the data gets saved in `OKCubot2/data`.

The data should always be saved in the same place by default. I proposed that we save it in `OKCubot2/data`.

One could add a call parameter, so that it gets saved into a specified location. I will look into adding another calling parameter.

**Comment by tomwalter2287** [comment]
Do you want to absolute path?

**Comment by Deleetdk** [comment]
In the command line argument? Yes.

**Comment by tomwalter2287** [comment]
Is it ok for you like:

python start.py user_name password ~/OKCubot2/data/

**Comment by tomwalter2287** [comment]
1. The data is saved in the same place by default(OKCubot2/data).
But you shouldn't change the project name, it must be OKCubot2 all the time.
2. I updated the image upload module to remove duplicated image.
The small thumbnail (82x82) is removed.

If you have other problems, let me know.

Regards

Tom

**Comment by tomwalter2287** [comment]
1. I add path to implement program in shell.
2. If you don't set path in shell, data will be saved in OKCubot2/data/ by default.

**Comment by Deleetdk** [comment]
This issue is now fixed.
