### ISSUE TITLE
User file/avoid scraping the same user twice if not necessary

### ISSUE THREAD

**Issue by Deleetdk** [Deleetdk/OKCubot2#3]
Currently, the scraper picks users at semi-random and scrapes them. Then picks some more, etc. Altho there are hundreds of thousands of users, doing it this way makes it possible that the same user will get scraped twice. This potentially wastes the scraper's time.

To avoid this problem, one can create a user file that keeps track of which users were scraped and number of questions answered and when they were scraped.

Creating the `users.csv` will be easy enough. Just a little change to `save_as_csv`. Then a change must be made to the scraper function (`get_target` I think?) so that it skips users that have not changed their data.

**Comment by tomwalter2287** [comment]
Sounds good!

**Comment by Deleetdk** [comment]
I have implemented saving the user info to `users.csv` in https://github.com/Deleetdk/OKCubot2/commit/0450111e30aca6d31e6a99dcec570631d2a14e61

It works on my end, but some settings were incorrectly changed I see.

**Comment by tomwalter2287** [comment]
So you want to remove the changes in .gitignore and settings.py in my part?

**Comment by Deleetdk** [comment]
Just use `git pull` before you use `git commit`. This updates your local version with the server's, so that there are no conflicts. Make sure that your `.gitignore` file is correct because otherwise you are uploading temporary files (those ending with ~) and data files (those in `data/`) to the repository. If you look at https://github.com/Deleetdk/OKCubot2/blob/master/.gitignore#L64 you will see that I have excluded these.

**Comment by tomwalter2287** [comment]
I pushed new version.

Looking forward to your response.

**Comment by tomwalter2287** [comment]
I pull your original project.
So this issue must be solved.

**Comment by tomwalter2287** [comment]
I think this issue is already solved.

**Comment by Deleetdk** [comment]
We need to test it. I tried testing it with the --u option. However, it still scrapes the user twice.

**Comment by tomwalter2287** [comment]
Twice?

It scrapes the user only once.

**Comment by Deleetdk** [comment]
If I run the scraper twice with the same user in --u, the profile is scraped twice. It should be skipped the second time if the number of questions answered in the profile is the same as the number in `users.csv`. Make sure that this skipping feature is disableable with a command line argument. E.g. --noskip.

**Comment by tomwalter2287** [comment]
Hi, Emil.

I pushed new version.
This issue is solved in this version.

**Comment by Deleetdk** [comment]
I tested this with user mama_crossasaur. This user has not answered any hidden questions. The code correctly skips her. I also tried the `--noskip` argument. Also worked.

```
python start.py PlainSeagull PlainSeagullPlainSeagull --u mama_crossasaur
python start.py PlainSeagull PlainSeagullPlainSeagull --u mama_crossasaur --noskip
```

There is a problem with users that have answered some questions privately. The scraper does not scrape them, so they do not get counted. However, the scraper uses the number shown in the profile to make the comparison, hence it still scrapes them.

The solution is to change the number used for the comparison to use the one shown in the profile as well. I will make this change myself.

**Comment by Deleetdk** [comment]
Can you add the number of questions answered to `target_info`? Call it `m_numberanswered`. In that case, I can get the information I need in the `save_as_csv` function.

**Comment by tomwalter2287** [comment]
I sent you new version.

**Comment by Deleetdk** [comment]
Good. I am currently doing a large test of the scraper (scraping 1000 users). I am looking to see if there are more bugs that we just haven't seen yet.

I will try your new version after I'm done with that.

**Comment by Deleetdk** [comment]
Fixed in https://github.com/Deleetdk/OKCubot2/commit/4b9a67aa9b37c8e48d8c8ac680c8d0958ac01db7
