### ISSUE TITLE
Scraper is possibly missing a few questions

### ISSUE THREAD

**Issue by Deleetdk** [Deleetdk/OKCubot2#4]
The switch from using the question categories to using the list of all questions helped towards getting more questions. However, I scraped some users and the scraper still may be missing some questions.
E.g. user https://www.okcupid.com/profile/storming/questions has 682 questions in common with the scraper profile, but the datafile has 677 of them. So, 5 are missing. This may be a bug in reading the last page of questions. Or it may be the user has hidden their answers to 5 questions.

I also scraped user https://www.okcupid.com/profile/casjgoon666/questions. The scraper gets 86 and the user has 86, so there is no error there.

**Comment by tomwalter2287** [comment]
I tested several target users, but there were no missing questions.
So I think storming hide 5 questions.

**Comment by Deleetdk** [comment]
Not a real bug, closing this.
