### ISSUE TITLE
Add command line argument to set the number of users to scrape

### ISSUE THREAD

**Issue by Deleetdk** [Deleetdk/OKCubot2#6]
Currently, the number of users to scrape is hardcoded in `okcubot_spider.py` in the function `OKcuSpider`. This should not be the case. It should have a default value (e.g. 1) and possibly take a value from the command line.

**Comment by Deleetdk** [comment]
Because the number of arguments is growing, it would be wise to change to using something like argparse. https://docs.python.org/2/howto/argparse.html The code currently uses `sys` for this, but it lacks features.

Using argparse allows us to use both positional and optional arguments. The necessary arguments are username and password (given in position 1 and 2). The optional are output location and number of users to scrape. These could be given the flags --o and --n for instance. E.g.:

`python start.py username userpass --o "~/okcupid_data/" --n 100`

**Comment by tomwalter2287** [comment]
Hi, Emil.

I pushed new version.

Please check it and let me know the result asap.

**Comment by Deleetdk** [comment]
Tom,

I tested both features and both worked.

**Comment by tomwalter2287** [comment]
Great!

So what's next?

**Comment by Deleetdk** [comment]
Fixing the other open issues.

**Comment by tomwalter2287** [comment]
What issues?

**Comment by tomwalter2287** [comment]
Hello?

**Comment by tomwalter2287** [comment]
Hello, Emil.

**Comment by tomwalter2287** [comment]
Looking forward to your response
