### ISSUE TITLE
Scrape a specific user

### ISSUE THREAD

**Issue by Deleetdk** [Deleetdk/OKCubot2#7]
For debugging purposes, it is useful if one can specify a specific user to scrape. I propose to add a command line argument (--u) to make this possible.

For instance, bugs like https://github.com/Deleetdk/OKCubot2/issues/5 are rare, so testing whether the code works for these cases may take some time.

**Comment by tomwalter2287** [comment]
Hello, Emil.

I added '--u' option.
Let me know the result asap.

**Comment by Deleetdk** [comment]
It works for me.
