### ISSUE TITLE
Image order

### ISSUE THREAD

**Issue by Deleetdk** [Deleetdk/OKCubot2#8]
I note that the primary picture (the one shown in the profile) is saved with the last number. It should be saved with the first (i.e. 1). This makes it easier to do analyses of the primary pictures.

E.g. https://www.okcupid.com/profile/Cloudy7_taco, her primary picture is saved as number 10.

**Comment by tomwalter2287** [comment]
I pushed new version.
This issue is solved in this version.

**Comment by Deleetdk** [comment]
I tested and it works for me now.
